# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: VMAgent

steps:
- task: Npm@1
  inputs:
    command: 'install'
#- task: Npm@1
#  inputs:
#    command: 'custom'
#    customCommand: 'install -g @angular/cli@16'

- task: CmdLine@2
  inputs:
    script: 'ng build'
