apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:  
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      imagePullSecrets:
      - name: imagepull

      volumes:
        - name: logs-storage
          emptyDir: {}
      containers:
      - name: webapp
        image: demoacrpractice123.azurecr.io/samplewebapp
        imagePullPolicy: Always
        volumeMounts:
          - name: logs-storage
            mountPath: /var/log/nginx
        ports:
        - containerPort: 80

      - name: busybox
        image: busybox:latest
        command: []
        args: []
        volumeMounts:
          - name: logs-storage
            mountPath: /data

---

apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: webapp
